// <auto-generated />
using LoanInformationAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LoanInformationAPI.Migrations
{
    [DbContext(typeof(LoanDBContext))]
    [Migration("20200908153725_LoanInformationAPI.Models.LoanDBContext")]
    partial class LoanInformationAPIModelsLoanDBContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LoanInformationAPI.Models.LoanDetails", b =>
                {
                    b.Property<string>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoanAmount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanHoldersBorrowerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoanTerm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanId");

                    b.HasIndex("LoanHoldersBorrowerName");

                    b.ToTable("LoanDetails");

                    b.HasData(
                        new
                        {
                            LoanId = "9034",
                            LoanAmount = "230000",
                            LoanTerm = "24 Months",
                            LoanType = "HOME Loan"
                        });
                });

            modelBuilder.Entity("LoanInformationAPI.Models.LoanHolder", b =>
                {
                    b.Property<string>("BorrowerName")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LegalDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoanId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyInformation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BorrowerName");

                    b.ToTable("loanHolders");

                    b.HasData(
                        new
                        {
                            BorrowerName = "Rajesh",
                            LegalDocuments = "House Tax central Govt",
                            LoanId = "9034",
                            PropertyInformation = "1-1-2,Infopark,Kochi,Kerala-682030"
                        });
                });

            modelBuilder.Entity("LoanInformationAPI.Models.RoleDescription", b =>
                {
                    b.Property<int>("Roleid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Roleid");

                    b.ToTable("RoleDescriptions");

                    b.HasData(
                        new
                        {
                            Roleid = 1,
                            RoleType = "Admin"
                        },
                        new
                        {
                            Roleid = 2,
                            RoleType = "User"
                        });
                });

            modelBuilder.Entity("LoanInformationAPI.Models.LoanDetails", b =>
                {
                    b.HasOne("LoanInformationAPI.Models.LoanHolder", "LoanHolders")
                        .WithMany("LoanDetailsList")
                        .HasForeignKey("LoanHoldersBorrowerName");
                });
#pragma warning restore 612, 618
        }
    }
}
